{% set name = "jupyterlab-lego-boost" %}
{% set version = "0.1.0a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_lego_boost-{{ version }}.tar.gz
  sha256: bd334f3398987a434d889142e2c8f6fa67d123154de4c1449c466e42a848e473

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.4
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - jupyterlab =3.4
  run:
    - python >=3.7
    - jupyterlab-blockly >=0.3.3,<0.4
    - bleak
    - pylgbst

test:
  imports:
    - jupyterlab_lego_boost
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QuantStack/jupyterlab-lego-boost
  summary: Blockly extension for JupyterLab to control the Lego Boost
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - hbcarlos
